version: '3'
services:
  ar:
    build: ./ar
    volumes:
      - ./ar:/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      KAFKA_HOST: kafka:9092

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dmzdb